### ISSUE TITLE
[Enhancement] Possible Tetra and TiCon integration for Enigmatic Fortunizer

### ISSUE THREAD

**Issue by Ridanisaurus** [Ridanisaurus/EmendatusEnigmatica#112]
**Mod Version**
1.16.5 1.2.10

https://github.com/NillerMedDild/Enigmatica6/issues/3252#issuecomment-921980781

**Comment by SuperKael** [comment]
May I add that the Enigmatic Fortunizer also does not allow Tetra pickaxes to be automatically removed under any circumstances, even once they are completely depleted of durability. As such, once the pickaxe breaks, it will get stuck until a player comes and removes the out-of-durability pickaxe manually.

To clarify, Tetra tools stop functioning at 1 durability rather than 0, which is why the Fortunizer never exports them.

**Comment by Ridanisaurus** [comment]
The Fortunizer is being completely removed in the V2
