### ISSUE TITLE
The bitumen of EE cannot be processed by the machine of TE5

### ISSUE THREAD

**Issue by Dr-WeiAL** [Ridanisaurus/EmendatusEnigmatica#115]
**Mod Version**
1.2.10

**Describe the bug/enhancement**
Unrecognized bitumen

**Expected behavior**
Can it be processed normally 

**Screenshots**
![image](https://user-images.githubusercontent.com/47446553/139921781-cecb7341-eb23-47eb-aa72-dceea2e885d4.png)
![image](https://user-images.githubusercontent.com/47446553/139921827-bf8495d2-fc23-41eb-8ff5-c6739be40ce8.png)

**Additional context**
TE5 refers to [Thermal](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)

**Comment by Ridanisaurus** [comment]
Chances are this is due to Thermal machine hardcorded to using their Bitumen, instead of a Forge Tag. This is not something I can fix at the moment. However, V2.0 of the mod will have as much integration as possible. Until then, you would need to create a custom recipe using KubeJS for exmaple.
Here is how we did it in E6: https://github.com/NillerMedDild/Enigmatica6/blob/master/kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge.js

**Comment by Dr-WeiAL** [comment]
I found that the item id of EE's bitumen is completely bitumen_gem, while the bitumen of TE5 is just bitumen. Could it be because of this problem?
Also I tried to use kubeJS, but it doesn’t seem to support pyrolyzer
