### ISSUE TITLE
rfttoolsbase

### ISSUE THREAD

**Issue by OddJarro** [Ridanisaurus/EmendatusEnigmatica#129]
Can't make any machine that uses dimensional shards because the recipes don't accept dimensional shards. now i have a bunch of useless dimensional shards

**Comment by Ridanisaurus** [comment]
1) Next time, please use the report template
2) EE only provides the building materials to modpack devs, and they have to do the rest by introducing some of the compat. While I do have some native recipes, some are still problematic, like the the RFTools ones, and that's due to hardcoding instead of using tag-based recipes from the mod side.
3) This will be solved in the new version as EE won't be registering items and blocks natively, instead It's going complete data-driven, so Modpack devs can make their own ores and materials, so this way if a modpack doesn't care about the Dim Shards, they can just skip it all together.
