### ISSUE TITLE
[Enhancement] Have Gold and Quartz active by default in the Nether

### ISSUE THREAD

**Issue by jinkhya** [Ridanisaurus/EmendatusEnigmatica#134]
**Mod Version**
EmendatusEnigmatica-1.2.15-build.7+mc1.16.5

**Describe the bug/enhancement**
With just EE and forge with no config change, nether quartz ore doesn't spawn in the nether. Turning generate_in_the_nether to true or false makes no difference.

**To Reproduce - if applicable**
1. Make an instance with forge 22 and EE1.2.15
2. Go to the nether to check if quartz ore is generating.

**Expected behavior**
Quartz ore to generate especially if generate_in_the_nether is set to true :)

Thanks in advance !
Jin

**Comment by jinkhya** [comment]
Same problem seems to happen to gold ore in the nether.

**Comment by jinkhya** [comment]
After some further investigation the vanilla ores for quartz and nether gold spawn in basalt biome only for some reason.

**Comment by Ridanisaurus** [comment]
The ones that spawn in the Basalt Deltas is the Vanilla Ores as I had some issues removing those due to Mojang hardcoding them big time.
With EE, you need to activate the Nether generation for Gold and Quartz from the config in order to find them in all Biomes. It seems that I forgot to have these active by default.
For now, you should be able to activate the Nether generation and make sure the Strata is also activated (i.e. Netherrack).
While I'm busy with the 1.18 port and refactoring, I will keep this item open so I can push a Release for 1.16.5 with a fix for this to have them active by default.

**Comment by jinkhya** [comment]
But that's the thing when i turn generate_in_the_nether to true they don't generate either :)

**Comment by jinkhya** [comment]
Oh! The strata that's probably it! Sorry about that then, that's me not using the config properly.

**Comment by jinkhya** [comment]
Yep it worked. Thanks a lot! Great mod btw :)
