### ISSUE TITLE
[BUG] EE Arcane ore has no recipes.

### ISSUE THREAD

**Issue by BastionNtB** [Ridanisaurus/EmendatusEnigmatica#29]
**Mod Version**
EmendatusEnigmatica-1.16.4-1.0.2.jar

**Describe the bug/enhancement**
I'm using this mod with Ars Nouveau (ars_nouveau-1.16.4-1.9.4.jar) the ore is generating, but your arcane ore variant that generates from your mod does not have any recipes. E.g. I can't smelt the arcane ore, or anything. Am I missing something?

**To Reproduce - if applicable**
1. Create Emendatus Arcane ore
2. Try to put in furnace with coal, nothing
3. Create Ars Nouveau Arcane ore
4. Try to put in furnace with coal, I get Ars Mana Gems.

**Expected behavior**
I expected to get the EE equivalent Arcane Chunk perhaps. (If that even is the equivalent)

**Screenshots**
N/A

**Additional context**
I've got quite a few extra mods. But if I'm barking up the wrong tree for this I may just disable the arcane ore from EE and keep Ars in. I don't know.

**Logs**
N/A

Thanks!

**Comment by Ridanisaurus** [comment]
Thanks, will look into it shortly.

**Comment by Ridanisaurus** [comment]
All non-Vanilla Gem Based ores have their Smelting/Blasting recipes disabled by default.
- 99.9% of the time the player will break them with Fortune to get Extra rolls on the Gem Loot-Table
- Most processing machines can do a better job at processing Gem ores than smelting
- Compact for this can be easily added by Modpack devs as a custom recipe if needed

**Comment by BastionNtB** [comment]
I'm not seeing this same issue for copper or tin, those are all functioning perfectly as expected. It was just Arcane that was acting strange. On a side note; Is there a benefit for those recipes being disabled by default?

**Comment by Ridanisaurus** [comment]
No particular benefit, but do bare in-mind that when EE was developed, it was somewhat custom made to Enigmatica Suite needs. However, I made sure that it is possible for other modpack developers to utilize this mod, and be able to add any 'missing' recipes through basic Datapacks. Only a handful of Gem based ores have a Smelting recipe beside the Vanilla ones (Coal, Redstone, Lapis, Emerald, and Diamond) as it's not really a standard thing in modded, like Fluorite from Mekanism for example. Even in Vanilla, no one in their right mind would smelt a Gem ore.

Regardless, as I said, recipes can be easily added through a basic Datapack, or if you prefer something with more control, KubeJS to the rescue.

**Comment by BastionNtB** [comment]
I guess I didn't really convey the issue properly. There are no recipes for the arcane ore. So like if I mined it, it would literally be a block with no use in any mod whatsoever. I'd have to toss it, or I guess decorations. I was trying to get that issue troubleshot if possible, but I guess what I'm hearing is, that it is indeed intended that way, and I need to add all basic recipes for it myself using other methods?

Not trying to be a pain or anything, just want to make sure I understand what direction I need to take. I'm building this for myself and a couple of friends, and I'm not really experienced with data packs and the kubejs thing is entirely new to me.

**Comment by Ridanisaurus** [comment]
Arcane Ore should drop the following when mined:
Fortune/Non-Enchanting => Mana Gem
Silktouch => Mana Chunk

The Mana Gem should be compatible with the Ars Nouveau Mana Gem due to tag sharing. If there are no usages, then you will need to allow it through scripts.
Remember, Emendatus Engimatica is a canvas for Modpack developers to build upon with their scripts for Unification. The only time it will work out of the box is when the machine/tile entities access Tag input instead of hardcoded recipes as all EE items are Forge tagged.
The Mana Chunk (or chunks in general) are technical an Ore Block in an item form. They have a conversion recipe to turn them back to blocks so you can mine them again at a later date with Fortune. This was implemented for those that like to go Mining with Silktouch.

If you want, feel free to reach out to me on Discord (Ridanisaurus Rid#3776) so we can discuss the current issues you are having with implementing it in your modpack live, and I'll be able to provide you with examples on how to use Datapacks/KubeJS to make that happen :)

**Comment by BastionNtB** [comment]
Dude, I feel like such an idiot. I didn't actually MINE IT.

You're absolutely correct, if I mine it outside of creative, it works just as I expected. I'm so sorry.

I've been so tunnel focused on testing interactions with mods that I haven't taken a second to actually try some of this stuff outside of creative lol

I might take you up on that offer, I'll try not to be too much of a bother, but I wouldn't mind seeing some examples of that stuff. Thank you
