### ISSUE TITLE
[Bug] X-ray using Fabulous graphics

### ISSUE THREAD

**Issue by Fuzzy2319** [Ridanisaurus/EmendatusEnigmatica#73]
**Mod Version**
1.1.5

**Describe the bug/enhancement**
You can see behind ores using Fabulous graphics

**To Reproduce - if applicable**
1. Put graphics to Fabulous
2. Look to an ore

**Expected behavior**
![image](https://user-images.githubusercontent.com/61144247/114168918-382f4000-9931-11eb-9170-4bc50a5d0f7d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/61144247/114169000-4da46a00-9931-11eb-8f0e-52f2176dcd9f.png)

**Comment by Ridanisaurus** [comment]
This is not really a bug in EE per se. You will get the same effect if you look at Water or Ice, or pretty much any block that is using the Translucent RenderType. This is due to 1) the Fabulous graphics being an experimental option, and 2) you not having a supported Graphics Card.

**Comment by Shadows-of-Fire** [comment]
Why exactly is this wontfix?  Why do your ores need to render in translucent?  These are fully solid blocks, they should not be rendering in the translucent layer unless they absolutely have to, as it tanks performance.

The x-ray thing does occur with ice, but the main thing it xrays to is *other ores* since they are also translucent.

**Comment by Ridanisaurus** [comment]
The Forge Multi-Layer is used because my mod adds metric ton of Ores, and creating a texture for each one of them is not a feasible option, 840 Textures to be exact. The solid layer is for the background and it inherits the resource location of the texture instead of a hardcoded texture, which also means players who like to use 32x32+ Resource Packs won't have a random 16x16 Stone Ore in the middle of their high-res caves. The translucent layer is used for the overlays, and it is set to translucent because the overlays of ores have translucent shadows casting on the stone behind them. 
I did try to use CUTOUT but without that shadow drop, they looked godawful.
As for performance, I tested it on multiple occasions, on multiple machines (including potato machines) and the impact was minimum to none-existent.

**Comment by mtjohnson47** [comment]
Why is the GTX 1070 not supported?  It's only a few generations old, and a high end card of its generation.

**Comment by Ridanisaurus** [comment]
I have a 1080ti, and that's not supported either. Anyways, this is a Vanilla issue. Like I said, it does the same on Ice and Water. Not something I can fix, at least not without jeopardizing my ores looking good, or creating metric ton of textures, especially that in EE V2.0 the addition of new ores will be done through JSONs, and the textures will be created automatically due to me going completely data-driven.
