### ISSUE TITLE
Ore textures appear to flicker when using any shader

### ISSUE THREAD

**Issue by SargeRyong** [Ridanisaurus/EmendatusEnigmatica#83]
**Mod Version**
1.16.5-1.2.4

**Describe the bug/enhancement**
The drawn-on parts of ore blocks appear to flicker rapidly while moving, especially when very close.  The effect looks like z-fighting.  After consulting with a shader dev, they added "nothing I can do about that. I don't change where their vertexes appear."

**Expected behavior**
Ore textures are clear and visible at all times.

**Screenshots**
https://i.imgur.com/FpkQ5yl.png
https://i.imgur.com/X54h3Yx.png

In the second image, the top blocks are emendatus enigmatica coal ore.  The bottom blocks are vanilla coal ore.

**Additional context**
Seems to occur with any shader / settings as far as I can tell.  With no shader (but still running optifine), textures are steady and do not flicker.

**Logs**
N/A, couldn't find any log messages anywhere that seemed to be relevant.

**Comment by Ridanisaurus** [comment]
I know it works with Shaders as I play with Shaders sometimes for some cinematic screenshots for E6. 
Will look into it later on and see what might be going on.

**Comment by SargeRyong** [comment]
> 
> 
> I know it works with Shaders as I play with Shaders sometimes for some cinematic screenshots for E6.
> Will look into it later on and see what might be going on.

Maybe it's only certain ones?  For what it's worth, I and players on my server were seeing it using BuildersQOL Shaders (https://cdn.discordapp.com/attachments/322099626104586250/823429918578573312/Builders_Modded_Shaders_V2.8.2.zip).  The ore textures flickering back into the stone textures are really the only strange artifact I've noticed.

I'll see if I can experiment with some others and see what causes it and what doesn't.

**Comment by SargeRyong** [comment]
Ah, yeah, its definitely not all shaders.  Tried out Complimentary today and they render just fine.  How strange.

**Comment by Ridanisaurus** [comment]
In that case it's Shader related issue.
Ores added by EE are dynamic, they are built to be 2 blocks occupying a single space, where the background block uses a texture resource instead of being hard-coded, and the foreground uses an ore overlay.
This system was developed so I can add as many stone types as I want, without the need to generate 30+ textures for each stone. It also allows players that use Resource Packs to have their updated stone texture used for the ores, which helps with maintaining the immersion for them.
I will proceed to close this incident as it should be fixed on the Shaders side.
