### ISSUE TITLE
[Suggestion] Make ore chunks texture "larger" and "chunkier" in size, ore texture suggestion

### ISSUE THREAD

**Issue by yavincl** [Ridanisaurus/EmendatusEnigmatica#88]
**Mod Version**
1.2.7 - 1.16.5

**Describe the bug/enhancement**
Hey there. While playing Enigmatica 6, I felt like the ore chunk textures were a little too small. Like, how do you smelt this tiny lump and it spouts into two big ingots? Basically I feel like the chunks should be retextured to be bigger like below. 

Also, if you could include the new ore block textures as overlays for the basic vanilla ores instead of the standardized ones, that'd be great! I have some experience with image editing and making pixel art (from astral sorcery), so I can help in importing/varying the overlays, because honestly the current lack of variety is really bothersome for me. I don't trust myself to touch the chunks right now since I don't know how to automate it, or to replicate the current style.

Here's the new 1.17 textures by Jappa
![yykq2yq41sr61](https://user-images.githubusercontent.com/57966308/122650854-7a33e980-d10b-11eb-8bea-c8cda6715c3f.png)

![new-ore-textures_8](https://user-images.githubusercontent.com/57966308/122650992-4dcc9d00-d10c-11eb-987e-fa3d50dcf369.png)

**Comment by Ridanisaurus** [comment]
Personally, I can't stand the new ores, and chances are EE Ores will maintain the old ores look for a long time, even when I port to 1.17. 
However, EE Ore Textures are built to be dynamic, so creating a Resource Pack is extremely easy as you only need to do it for the Overlays, and not for every single Ore Block. 
Therefore, I will leave this up to the players to create their own textures if they desire to have the new look.

As for the chunks, they are smaller because you can combine 4x Chunks into Clusters which have a larger texture.
Again, as these are just textures, if someone wants to create a Resource Pack to use different textures for the chunks, they are more than welcome to do so.
